"""Token-bucket rate limiting with per-customer enforcement and abuse detection.

Enforces per-customer QPS limits using the token-bucket algorithm.
Detects abuse patterns (e.g., database scraping via systematic queries)
and triggers automated throttling with admin alerts.
"""

from __future__ import annotations

import logging
import time
from collections import defaultdict

from pydantic import BaseModel, ConfigDict

logger = logging.getLogger(__name__)


class RateLimitResult(BaseModel):
    """Result of a rate-limit check."""

    model_config = ConfigDict(frozen=True)

    allowed: bool
    remaining_tokens: float
    retry_after_seconds: float | None
    customer_id: str


class AbuseAlert(BaseModel):
    """Alert generated by the abuse detector."""

    model_config = ConfigDict(frozen=True)

    customer_id: str
    pattern: str
    detail: str
    timestamp: float
    recommended_action: str


class TokenBucket:
    """Token-bucket rate limiter for a single customer."""

    def __init__(self, *, rate: float, capacity: float) -> None:
        self._rate = rate
        self._capacity = capacity
        self._tokens = capacity
        self._last_refill = time.monotonic()

    def _refill(self) -> None:
        now = time.monotonic()
        elapsed = now - self._last_refill
        self._tokens = min(self._capacity, self._tokens + elapsed * self._rate)
        self._last_refill = now

    def consume(self, tokens: float = 1.0, *, customer_id: str = "") -> RateLimitResult:
        """Attempt to consume tokens. Returns whether the request is allowed."""
        self._refill()
        if self._tokens >= tokens:
            self._tokens -= tokens
            return RateLimitResult(
                allowed=True,
                remaining_tokens=self._tokens,
                retry_after_seconds=None,
                customer_id=customer_id,
            )
        retry_after = (tokens - self._tokens) / self._rate if self._rate > 0 else 1.0
        return RateLimitResult(
            allowed=False,
            remaining_tokens=self._tokens,
            retry_after_seconds=retry_after,
            customer_id=customer_id,
        )


class AbuseDetector:
    """Detects abuse patterns across customer requests."""

    def __init__(
        self,
        *,
        window_seconds: float = 60.0,
        burst_threshold: int = 100,
        identical_threshold: int = 10,
    ) -> None:
        self._window_seconds = window_seconds
        self._burst_threshold = burst_threshold
        self._identical_threshold = identical_threshold
        self._request_timestamps: defaultdict[str, list[float]] = defaultdict(list)
        self._query_hashes: defaultdict[str, defaultdict[str, int]] = defaultdict(
            lambda: defaultdict(int)
        )

    def _prune_window(self, customer_id: str) -> None:
        cutoff = time.monotonic() - self._window_seconds
        ts_list = self._request_timestamps[customer_id]
        self._request_timestamps[customer_id] = [
            t for t in ts_list if t > cutoff
        ]

    def record_request(
        self, *, customer_id: str, query_hash: str
    ) -> AbuseAlert | None:
        """Record a request and check for abuse patterns."""
        now = time.monotonic()
        self._request_timestamps[customer_id].append(now)
        self._query_hashes[customer_id][query_hash] += 1
        self._prune_window(customer_id)

        # Check burst
        if len(self._request_timestamps[customer_id]) > self._burst_threshold:
            return AbuseAlert(
                customer_id=customer_id,
                pattern="high_frequency_burst",
                detail=(
                    f"{len(self._request_timestamps[customer_id])} "
                    f"requests in {self._window_seconds}s window"
                ),
                timestamp=now,
                recommended_action="throttle",
            )

        # Check identical queries
        if self._query_hashes[customer_id][query_hash] > self._identical_threshold:
            return AbuseAlert(
                customer_id=customer_id,
                pattern="repeated_identical",
                detail=(
                    f"Query hash {query_hash} repeated "
                    f"{self._query_hashes[customer_id][query_hash]} times"
                ),
                timestamp=now,
                recommended_action="review",
            )

        return None


class RateLimiterRegistry:
    """Registry of per-customer token buckets with abuse detection."""

    def __init__(self) -> None:
        self._buckets: dict[str, TokenBucket] = {}
        self._detector = AbuseDetector()
        self._alerts: list[AbuseAlert] = []

    def get_or_create(
        self, *, customer_id: str, rate: float, capacity: float
    ) -> TokenBucket:
        """Get existing bucket or create a new one for the customer."""
        if customer_id not in self._buckets:
            self._buckets[customer_id] = TokenBucket(rate=rate, capacity=capacity)
        return self._buckets[customer_id]

    def check(
        self,
        *,
        customer_id: str,
        rate: float,
        capacity: float,
        query_hash: str = "",
    ) -> RateLimitResult:
        """Check rate limit and record request for abuse detection."""
        bucket = self.get_or_create(
            customer_id=customer_id, rate=rate, capacity=capacity
        )
        result = bucket.consume(customer_id=customer_id)

        if query_hash:
            alert = self._detector.record_request(
                customer_id=customer_id, query_hash=query_hash
            )
            if alert is not None:
                self._alerts.append(alert)
                logger.warning(
                    "Abuse alert for customer %s: %s", customer_id, alert.pattern
                )

        return result

    def get_alerts(self) -> list[AbuseAlert]:
        """Return and clear pending abuse alerts."""
        alerts = list(self._alerts)
        self._alerts.clear()
        return alerts

    def stats(self) -> dict[str, dict[str, float]]:
        """Return per-customer stats."""
        result: dict[str, dict[str, float]] = {}
        for cid, bucket in self._buckets.items():
            bucket._refill()
            result[cid] = {"remaining_tokens": bucket._tokens}
        return result
